backend:
  name: github
  repo: theleoji/lumos

media_folder: static/assets
public_folder: assets

collections:
  - name: pages
    label: Pages
    folder: content/pages
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: description, label: Description }
      - {
          name: show_nav,
          label: "Show in Navigation?",
          widget: "boolean",
          required: false,
        }
      - {
          name: nav_order,
          label: "Navigation order",
          widget: "number",
          required: false,
        }
      - { name: external_link, label: "Redirect URL", required: false }
      - { name: body, label: Body, widget: markdown }
