[build]
  publish = "./public"
  command = "yarn run build"

[[plugins]]
package = "netlify-plugin-gatsby-cache"

[[redirects]]
  from = "https://leoji.dev/*"
  to = "https://leoji.codes/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.leoji.codes/*"
  to = "https://leoji.codes/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://theleoji.netlify.app/*"
  to = "https://leoji.codes/:splat"
  status = 301
  force = true